name: Publish Test docs
on:
  pull_request:
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  publish-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Clean Project
        run: ./gradlew clean
      - name: Generate Docs
        run: ./gradlew dokkaHtml
      - name: Sync Docs
        run: ./gradlew syncDocs
      - name: Deploy root docs to website
        if: ${{ github.repository == 'episode6/redux-store-flow' }}
        uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: docs
          TARGET_FOLDER: /
          CLEAN: true
      - name: Deploy dokka to website
        if: ${{ github.repository == 'episode6/redux-store-flow' }}
        uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: build/dokka/html
          TARGET_FOLDER: /docs/${{ github.ref }}/
          CLEAN: true

